FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential python3 python3-pip python3-requests python3-numpy python3-pyproj python3-gdal python3-shapely python3-rtree python3-pil python3-pil.imagetk p7zip-full libnvtt-bin freeglut3

COPY . /repo
WORKDIR /repo/Utils
RUN gcc triangle.c -lm

FROM ubuntu:20.04 as package
COPY --from=builder /repo/Utils/triangle /
